### ISSUE TITLE
Update Pathfinder API

### ISSUE THREAD

**Issue by MarvinTorres** [kytos/pathfinder#61]
**Note:** I have temporarily paused development on this issue.

@hdiogenes 

Currently, users are unable to specify standards that returned best paths will meet. An updated API that would allow them to set those standards is needed.

### Tasks
- [x] Put updated API documentation up for review via pull request
- [ ] Make changes from reviewer feedback
- [ ] Receive approval from reviewers
